matrix:
  include:
    - language: php
      dist: precise
      php:
        - 5.6
        - 7.2
        - hhvm
      env:
        - CI_VERSION=3.1.9
        - DB=pdo/mysql

      sudo: false

      # install vanilla CI before anything
      before_install:
        - cd api/v1
        - wget https://github.com/bcit-ci/CodeIgniter/archive/$CI_VERSION.tar.gz -O - | tar xz
        - cp -r application/* CodeIgniter-$CI_VERSION/application/
        - cp -r system/* CodeIgniter-$CI_VERSION/system/
        - sh -c "composer install --dev --no-progress"
        - sh -c "if [ '$DB' = 'mysql' ] || [ '$DB' = 'mysqli' ] || [ '$DB' = 'pdo/mysql' ]; then mysql -e 'create database IF NOT EXISTS ci_test;'; fi"

      # install this project on top of it
      install:
        - cp -r CodeIgniter-$CI_VERSION/system/* system/
        - cp -r CodeIgniter-$CI_VERSION/application/* application/
        - mv CodeIgniter-$CI_VERSION/index.php index.php
        - rm -rf CodeIgniter-$CI_VERSION

      script:
        - phpunit
        - phpunit -c tests/phpunit.xml
